update the install script to install bioperl, biographics, and biosamtools seperately
git-svn-id: https://cbilsvn.pmacs.upenn.edu/svn/apidb/ApiCommonWebsite/trunk@46109 735e2a04-f8fc-0310-8a1b-f2942603c481

diff --git a/Model/bin/install_gbrowse2 b/Model/bin/install_gbrowse2
--- a/Model/bin/install_gbrowse2
+++ b/Model/bin/install_gbrowse2
@@ -8,7 +8,9 @@
 
 GBROWSE_TAR_PATH=$PROJECT_HOME/ApiCommonWebsite/Site/doc/gbrowse
 GBROWSE_TAR_FILE=GBrowse-2.39.tar.gz
-BIOPERL_TAR_FILE=bioperl_1.60_biographics_2.11_samtools_1.29.tar.gz
+BIOPERL_TAR_FILE=BioPerl-1.6.1.tar.gz
+BIOGRAPHICS_TAR_FILE=Bio-Graphics-2.26.tar.gz
+BIOSAMTOOLS_TAR_FILE=Bio-SamTools-1.33.tar.gz
 
 BUILD_DIR=$GBROWSE_TAR_PATH/gbrowse_build_tmp
 
@@ -70,7 +72,7 @@ post_install_clean() {
     fi
 }
 
-# unpack and install pre-made BioPerl 5 into cgi-lib
+# unpack and install pre-made BioPerl v1.6.1 into cgi-lib
 install_local_bioperl() {
     echo "INSTALL: installing bioperl...."
     echo "tar zxf $GBROWSE_TAR_PATH/$BIOPERL_TAR_FILE"
@@ -85,12 +87,46 @@ install_local_bioperl() {
     fi
 }
 
+# unpack and install pre-made BioGraphics v2.26 into cgi-lib
+install_local_biographics() {
+    echo "INSTALL: installing bioperl...."
+    echo "tar zxf $GBROWSE_TAR_PATH/$BIOGRAPHICS_TAR_FILE"
+    if ! tar zxf \
+        $GBROWSE_TAR_PATH/$BIOGRAPHICS_TAR_FILE \
+        -C $cgilibTargetDir 2> /dev/null; then
+        echo "FATAL: Unable to un-tar BioGraphics package '$GBROWSE_TAR_PATH/$BIOGRAPHICS_TAR_FILE'. Exiting..."
+        echo "tar zxf \
+        $GBROWSE_TAR_PATH/$BIOGRAPHICS_TAR_FILE \
+        -C $cgilibTargetDir"
+        exit 1
+    fi
+}
+
+# unpack and install pre-made BioSamTools v1.33 into cgi-lib
+install_local_biosamtools() {
+    echo "INSTALL: installing bioperl...."
+    echo "tar zxf $GBROWSE_TAR_PATH/$BIOSAMTOOLS_TAR_FILE"
+    if ! tar zxf \
+        $GBROWSE_TAR_PATH/$BIOSAMTOOLS_TAR_FILE \
+        -C $cgilibTargetDir 2> /dev/null; then
+        echo "FATAL: Unable to un-tar BioSamTools package '$GBROWSE_TAR_PATH/$BIOSAMTOOLS_TAR_FILE'. Exiting..."
+        echo "tar zxf \
+        $GBROWSE_TAR_PATH/$BIOSAMTOOLS_TAR_FILE \
+        -C $cgilibTargetDir"
+        exit 1
+    fi
+}
+
 configure_gb() {
 
     
     mkdirs
     
     install_local_bioperl
+
+    install_local_biographics
+
+    install_local_biosamtools
     
     export PERL5LIB=$cgilibTargetDir:$PERL5LIB
     if ! perl -e 'use Bio::Perl 1.5' 2> /dev/null; then
